# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker compose build
#      Start app: docker compose up app
# Start database: docker compose up db
# Run migrations: docker compose run migrate
#       Stop all: docker compose down (add -v to wipe db)
#
#version: '3.7'
volumes:
  florshopcore_db_data:
    name: "FlorShopCoreDBVolume"
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ssd/FlorShopCore/pgdata"
      o: bind
  florshopcore_app_data:
    name: "FlorShopCoreAppVolume"
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ssd/FlorShopCore/images"
      o: bind

services:
  app:
    image: florshopcore:latest
    container_name: FlorShopCore
    build:
      context: .
    env_file:
      - .env.development
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - florshopcore_app_data:/app/images  # Montaje del volumen para im√°genes en produccion
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: florshopcore:latest
    build:
      context: .
    env_file:
      - .env.development
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: florshopcore:latest
    build:
      context: .
    env_file:
      - .env.development
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:16-alpine
    container_name: FlorShopCoreDB
    volumes:
      - florshopcore_db_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.development
    ports:
      - '5432:5432'
